version: "3.8"
services:
  wca_on_rails:
    build:
      context: WcaOnRails
      target: "base"
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: wca_db
      WEBPACKER_DEV_SERVER_HOST: wca_webpacker
      VAULT_ADDR: "http://wca_vault:8200"
      VAULT_DEV_ROOT_TOKEN_ID: aDGdUASDGIUASGDKI
    working_dir: /app/WcaOnRails
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    tty: true
    # First, install Ruby and Node dependencies
    # Next, wait for the database to be ready for queries via https://stackoverflow.com/a/53717981/2558618
    # Load the database if it does not exist yet
    # Start the server and bind to 0.0.0.0 (vs 127.0.0.1) so Docker's port mappings work correctly
    command: >
      bash -c 'bundle install && yarn install &&
      while ! mysql --host=wca_db --user=root -e "SELECT 1" >/dev/null 2>&1; do
        echo "Waiting for MySQL to be ready" && sleep 5 ;
      done &&
      echo "MySQL is ready!" &&
      if ! [[ "`mysqlshow --user=root --host=wca_db wca_development`" =~ "Tables" ]] ;
        then echo "Populating development db, this will take a while" && bin/rake db:reset ;
      fi &&
      bin/rails server -b 0.0.0.0'
    depends_on:
      - wca_db
    networks:
      - wca-main

  wca_webpacker:
    build:
      context: WcaOnRails
    ports:
      - "3035:3035"
    environment:
      DATABASE_HOST: wca_db
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      VAULT_ADDR: "http://wca_vault:8200"
      VAULT_DEV_ROOT_TOKEN_ID: aDGdUASDGIUASGDKI
    working_dir: /app/WcaOnRails
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    command: >
      bash -c 'bundle install && yarn install &&
      bin/webpacker-dev-server'
    depends_on:
      - wca_on_rails
    networks:
      - wca-main

  wca_db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    volumes:
      - wca_db_volume:/var/lib/mysql
      - ./docker/my.cnf:/etc/my.cnf
    # Suppress unneeded messages via https://stackoverflow.com/a/55706057/2558618
    cap_add:
      - SYS_NICE
    networks:
      - wca-main

  wca_vault:
    image: hashicorp/vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=aDGdUASDGIUASGDKI
    volumes:
      - ./docker/vault/config:/vault/config
      - ./docker/vault/file:/vault/file
      - ./docker/vault/logs:/vault/logs
      - ./docker/vault/plugins:/vault/plugins
    ports:
      - "8200:8200"
    networks:
      - wca-main
volumes:
  wca_db_volume:
    driver: local
  gems_volume:
    driver: local

networks:
  wca-main:
    name: wca-main
