version: "3.7"
volumes:
  phpmyadmin_data:

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    environment:
      - PMA_HOST=wca_db
      - PMA_USER=root
      - PMA_PASSWORD=
    volumes:
      - phpmyadmin_data:/var/www/html/
    networks:
      - wca-main

  nginx:
    image: nginx:1.17.4-alpine
    volumes:
      - ./docker/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - phpmyadmin_data:/var/www/html/:ro
    ports:
      - "8000:8000"
    networks:
      - wca-main
    depends_on:
      - phpmyadmin
