openapi: 3.1.0
title: WCA API Documentation
summary: Documentation of the WCA internal APIs, currently in progress
description: These are API endpoints that are only available internally
contact:
  name: WCA Software Team
  url: https://www.worldcubeassociation.org
  email: software@worldcubeassociation.org
version: 0.0.1
servers:
  - url: http://localhost:3000/api/internal
    description: The production API server
paths:
  /{personId}/results/:
    get:
      summary: Get competition results for a person
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonResultsResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Person:
      type: object
      required:
        - id
        - name
        - wca_id
        - country_iso2
        - url
      properties:
        id:
          type: integer
          example: 267
        name:
          type: string
          example: "Tim Reynolds"
        wca_id:
          type: string
          example: "2005REYN01"
        country_iso2:
          type: string
          example: "US"
        url:
          type: string
          format: uri
          example: "https://www.worldcubeassociation.org/persons/2005REYN01"
    Rank:
      type: object
      required:
        - id
        - personId
        - eventId
        - best
        - worldRank
        - continentRank
        - countryRank
      properties:
        id:
          type: integer
        personId:
          type: string
        eventId:
          type: string
        best:
          type: integer
        worldRank:
          type: integer
        continentRank:
          type: integer
        countryRank:
          type: integer
    Medals:
      type: object
      required:
        - gold
        - silver
        - bronze
        - total
      properties:
        gold:
          type: integer
        silver:
          type: integer
        bronze:
          type: integer
        total:
          type: integer
    Records:
      type: object
      required:
        - national
        - continental
        - world
        - total
      properties:
        national:
          type: integer
        continental:
          type: integer
        world:
          type: integer
        total:
          type: integer
    Result:
      type: object
      required:
        - id
        - pos
        - best
        - average
        - name
        - country_iso2
        - competition_id
        - event_id
        - round_type_id
        - format_id
        - wca_id
        - attempts
        - best_index
        - worst_index
        - regional_single_record
        - regional_average_record
      properties:
        id:
          type: integer
        pos:
          type: integer
        best:
          type: integer
        average:
          type: integer
        name:
          type: string
        country_iso2:
          type: string
        competition_id:
          type: string
        event_id:
          type: string
        round_type_id:
          type: string
        format_id:
          type: string
        wca_id:
          type: string
        attempts:
          type: array
          items:
            type: integer
        best_index:
          type: integer
        worst_index:
          type: integer
        regional_single_record:
          type: string
          nullable: true
        regional_average_record:
          type: string
          nullable: true
    PersonResultsResponse:
      type: object
      required:
        - person
        - previous_persons
        - ranks_average
        - ranks_single
        - medals
        - records
        - championship_podiums
        - results
      properties:
        person:
          $ref: '#/components/schemas/Person'
        previous_persons:
          type: array
          items:
            type: object
        ranks_single:
          type: array
          items:
            $ref: '#/components/schemas/Rank'
        ranks_average:
          type: array
          items:
            $ref: '#/components/schemas/Rank'
        medals:
          $ref: '#/components/schemas/Medals'
        records:
          $ref: '#/components/schemas/Records'
        championship_podiums:
          type: object
          properties:
            world:
              type: array
              items:
                type: object
            continental:
              type: array
              items:
                type: object
            greater_china:
              type: array
              items:
                type: object
            national:
              type: array
              items:
                type: object
        results:
          type: array
          items:
            $ref: '#/components/schemas/Result'
