development:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

test:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

production:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
  url: <%= ENV.fetch("ANYCABLE_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: wca_production
