name: 'Build and Push JS Docker Image'
description: 'A custom action to build and push our Docker images with environment-specific configurations.'
inputs:
  target:
    description: 'Docker build target'
    required: true
  registry:
    description: 'Docker registry to push the image to'
    required: true
  tag:
    description: 'The image tag in the registry'
    required: true
outputs:
  imageid:
    description: 'The Docker image id build'
    value: ${{ steps.build-image.outputs.imageid }}
runs:
  using: 'composite'
  steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      id: build-js-image
      with:
        push: true
        context: ./next-frontend
        target: ${{ inputs.target }}
        tags: |
          ${{ inputs.registry }}:${{ inputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
